### ISSUE TITLE
Desync with host

### ISSUE THREAD

**Issue by Setterin** [AdamDX1337/AdamHook#1]
I am not a host, and when I try to use the features of the program, after about six months to a year of playing, it gets out of sync with the host and starts syncing with the save file, and then changes made using the program, such as instant construction, disappear. Is there any possibility to eliminate the unsynchronization?

**Comment by AdamDX1337** [comment]
SP Cheats only work in Singleplayer, so Research On click, instant construction, and so on. They will always desync games and thats unchangeable, if you want to use cheats in MP only use the "MP Cheats" side. (Which also has a chance to desync but much less likely)
