### ISSUE TITLE
Guide to the new features

### ISSUE THREAD

**Issue by Likuatontid** [AdamDX1337/AdamHook#2]
Hi. Since you're not adding any new features yet I'd like to try to do it myself. For example, manually adding political power or something like that, can you tell me how to do it? I'd like to see a guide or something so I can add to your project myself

**Comment by Likuatontid** [comment]
I tried manually finding static addresses for dynamic variable values (like political power or basic stability), but I have no luck.
However, the switch values are fine, like those with a value of 0 or 1, like fow for example

**Comment by AdamDX1337** [comment]
Make sure your looking at the right type, so political power isnt 4 bytes or a byte, its a float.
Secondly, from what ive seen, basically anything that isnt just a flip between 1 or 0 cant be found as a value in CE, instead you need to find the specific code inside hoi4 that executes the function and go in and change it yourself...

For example here is the dynamic address I found for political power, the value in CE is crazy and I cant seem to find a pointer, I presume that means you need to make an actual script that intercepts part of the code and runs your own (I dont know how to do yet)
![image](https://github.com/AdamDX1337/AdamHook/assets/141924413/e05d45b5-0b57-4c96-958e-441d8506f7b8)
![image](https://github.com/AdamDX1337/AdamHook/assets/141924413/d45f5bab-a75b-4c44-9700-ff1fb1484c2e)
![image](https://github.com/AdamDX1337/AdamHook/assets/141924413/b0e3394c-9b2e-4025-a777-d68445af4a68)

**Comment by AdamDX1337** [comment]
> Hi. Since you're not adding any new features yet I'd like to try to do it myself. For example, manually adding political power or something like that, can you tell me how to do it? I'd like to see a guide or something so I can add to your project myself

If your looking more for a huide on how to create an application to do it, like how I have a window that can change values instead of using CE, I can do that... but IDK about things like political power and stability, my main goal was for it to be multiplayer cheats anyways.

**Comment by Likuatontid** [comment]
Yes, I would love to see such an app. I understand that the values by political power type are floating point values, so I tried searching using "value from and to", i.e. if political power is 1500, I searched for values from 1499 to 1501, but still nothing. I think the real issue is that such values can't be found via CE.

**Comment by Likuatontid** [comment]
I found one CE table that was capable of editing the value of a political power's static address, but I never figured out how it did it.

**Comment by Likuatontid** [comment]
By the way, on the stability example, specifically the base stability, which is not a floating point value but rather a 4 byte value, I still couldn't even find a dynamic address for it.

**Comment by Likuatontid** [comment]
By the way, may I ask how you check which category you put a particular cheat in: SP/MP Cheats?
Do you somehow check if there is any unsynchronization in the network game when using them?

**Comment by AdamDX1337** [comment]
> Yes, I would love to see such an app. I understand that the values by political power type are floating point values, so I tried searching using "value from and to", i.e. if political power is 1500, I searched for values from 1499 to 1501, but still nothing. I think the real issue is that such values can't be found via CE.

I just showed that the value for political power is a completely crazy number, like 2000pp is 1.4823458E23-21 and 1889 is1.4823458E23-20 or something....

**Comment by AdamDX1337** [comment]
> BTW, may I ask how you check which category you put a particular cheat in: SP/MP Cheats? Do you somehow check if there is any unsynchronization in the network game when using them?

Pretty much, whatever doesnt desync (or just shouldnt, so tagswitch or fow) goes into MP, while things they always desync goes in SP.

**Comment by Likuatontid** [comment]
How did you find this variable with this crazy value of political power?

**Comment by Likuatontid** [comment]
Can I get your telegram contacts or similar? Or if you answer your mail. I found a pointer for political power and want to help, but I'm a noob in terms of code.
